version: "3.8"

services:
    beeroomie_db:
        image: postgres:latest
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - ${PGDATA_PATH}:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        networks:
            - db_network

networks:
    db_network:
        driver: bridge
